version: "3"

services:
  app:
    image: golang:1.11.4
    volumes:
      - .:/go/src/github.com/faroyam/pic-resizer
    working_dir: /go/src/github.com/faroyam/pic-resizer
    command: go run main.go
    ports:
      - "8080:8080"
